# -*- coding: utf-8 -*-
"""
/***************************************************************************
 doencas_obrigatorias
                                 A QGIS plugin
 Quantidade de ocorrências por zona de doença de publicação obrigatória
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-01
        copyright            : (C) 2021 by AutoGis Corporation
        email                : angecas91@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load doencas_obrigatorias class from file doencas_obrigatorias.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .doencas_obg import doencas_obrigatorias
    return doencas_obrigatorias(iface)
